language: cpp
env:
  - CMAKE_GENERATOR="Unix Makefiles"
  - CMAKE_GENERATOR="Ninja"
before_install:
  - git submodule update --init --recursive
  - sudo apt-add-repository -y ppa:kalakris/cmake
  - gem install coveralls-lcov mdl
  - sudo pip install cmakelint polysquare-generic-file-linter
  - sudo apt-get update -qq
  - sudo apt-get install -qq `cat DEPENDENCIES`
  - cmake --version
script:
  - mkdir -p test/build
  - pushd test/build
  - cmake ..  -DCMAKE_UNIT_LOG_COVERAGE=1
  - ctest --output-on-failure &&
  - popd
  # Find all errors except:
  # 1. Spaces between control and condition (preferred style)
  # 2. Indentation errors
  - find . -type f -name "*.cmake" -not -path "./test/build/*"| xargs cmakelint --spaces=4 --filter=-whitespace/extra,-whitespace/indent > .cmake-lint-log
  - cat .cmake-lint-log
  # Fails if file has length
  - echo "! [ -s .cmake-lint-log ]" > .check-link-script.bash
  - bash .check-link-script.bash
  # Lint markdown files
  - mdl .
  # Lint files for polysquare style guide
  - find . -type f -name "*.cmake" -not -path "./test/build/*" -not -path "./cmake-unit/*" -not -path "./determine-header-language/*" -not -name "*FileForCoverage.cmake" | xargs polysquare-generic-file-linter
  - find . -type f -name "CMakeLists.txt" -not -path "./test/build/*" -not -path "./cmake-unit/*" -not -path "./determine-header-language/*" | xargs polysquare-generic-file-linter
after_success:
  - cmake -DTRACEFILE=test/build/PolysquareToolingUtilTests.trace -DLCOV_OUTPUT=test/build/coverage.info -P cmake-unit/CMakeTraceToLCov.cmake
  - coveralls-lcov test/build/coverage.info
  - popd
